defaultPlacement: end
fieldLayouts:
  c34d61ac-0959-428c-8d69-0e5618cf23e2:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            uid: af7b4e58-a0e6-4506-84de-c233dc1c2de8
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 6a64df82-84c5-4ad0-bcac-55dc3b946283
        userCondition: null
handle: sortOptions
name: 'Sort Options'
siteSettings:
  2c2e1c6a-eb4d-44f1-9a43-8d79b326f354: # ES
    hasUrls: true
    template: null
    uriFormat: 'sort-options/{slug}'
  547128fa-4529-4483-9968-66425996b69f: # EN
    hasUrls: true
    template: null
    uriFormat: 'sort-options/{slug}'
structure:
  maxLevels: null
  uid: 41535823-ff5a-4d78-a1ea-ba40eb9521ae
