field: 17b9b8a2-978a-4cd8-a7da-f5b3d77e1ed3 # Graph Bars
fieldLayouts:
  8a95b17e-7545-4c01-9134-3976d2087dd0:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 4e2a01a5-ed3f-4652-9d31-4c064ff91cc1 # Label
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6ee7d3ff-995b-481a-9ee4-7412a780e98b
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 4d4bea1a-66b1-4042-b30d-b5525fa9481d # Y-value
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: add357e9-ff1e-4020-9cd6-6fa6ab1d2ba7
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 2482d99f-61cc-4d08-8df8-96297ca5a297
        userCondition: null
fields:
  4d4bea1a-66b1-4042-b30d-b5525fa9481d: # Y-value
    columnSuffix: jjbpkmpr
    contentColumnType: text
    fieldGroup: null
    handle: yValue
    instructions: null
    name: Y-value
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  4e2a01a5-ed3f-4652-9d31-4c064ff91cc1: # Label
    columnSuffix: fsbtlope
    contentColumnType: text
    fieldGroup: null
    handle: label
    instructions: null
    name: Label
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\PlainText
handle: bar
name: Bar
sortOrder: 1
