field: 839bfa4f-5a09-4b32-b1eb-e0fef7b7beda # Table Row
fieldLayouts:
  571dd5c9-3e02-467e-8105-1af7ae0d02bc:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 635c41e4-29a8-42de-965b-e30c5beb0685 # Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 98120f84-d291-4b55-a77b-45490f1beb42
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 9c099f02-5f47-4c2f-bf83-574a21fae092 # Equation
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ee4e3d39-c6b7-4966-82c2-087428531ec4
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 61a20ed7-0640-4792-9270-46e04f5c614a
        userCondition: null
fields:
  9c099f02-5f47-4c2f-bf83-574a21fae092: # Equation
    columnSuffix: ysrwuqji
    contentColumnType: text
    fieldGroup: null
    handle: equation
    instructions: null
    name: Equation
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: true
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  635c41e4-29a8-42de-965b-e30c5beb0685: # Text
    columnSuffix: bdhqzilz
    contentColumnType: text
    fieldGroup: null
    handle: text
    instructions: null
    name: Text
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\PlainText
handle: rowHeader
name: 'Row Header'
sortOrder: 2
