field: 8b781860-2b8c-4100-969a-2f13c5272420 # Table Row
fieldLayouts:
  8345db03-f9b8-417d-9be2-9bc20af3a4e1:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 7fd2ba5e-d840-47df-8c79-a5fd54ff5aae # Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1393a9df-93b3-4fc1-9fd5-9e0420b08ad9
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 7880478d-205c-4689-82fe-f4b69acd39e0 # Equation
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2a8d80ec-8884-40fd-8675-22e096e72f78
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: cf97be16-ade0-4f2a-be63-9b34ba88e973
        userCondition: null
fields:
  7fd2ba5e-d840-47df-8c79-a5fd54ff5aae: # Text
    columnSuffix: asssbrrc
    contentColumnType: text
    fieldGroup: null
    handle: text
    instructions: null
    name: Text
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\PlainText
  7880478d-205c-4689-82fe-f4b69acd39e0: # Equation
    columnSuffix: hmqtcujr
    contentColumnType: text
    fieldGroup: null
    handle: equation
    instructions: null
    name: Equation
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: true
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: rowHeader
name: Header
sortOrder: 3
