field: d18f36fd-9d74-4ba6-b860-25958b1d9182 # Alert Sources
fieldLayouts:
  1567bbb2-1095-40c2-b699-b8e297fdcb6c:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 0ec5fc47-5e4f-4591-a76e-745ef7078387 # Source Type
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c50a9874-9f0a-4453-9d98-b4b1c1f0eab0
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 4941158b-702a-45b4-8da5-12ed4202efae # Name
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 62113937-c37c-45b7-9a7e-eb13a42f43dc
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: f7469ef4-1cc6-4236-9a47-b0a7cad50b6a # X
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: de9bf237-7dd6-4738-b60e-2e5b7659f009
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: b23a622a-4c70-4e4d-be4a-3b2fbc739d19 # Y
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 38f42cd1-a8d6-4be6-9cd3-0ea5299fb291
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 00e7fda5-a5ff-4422-81e4-60b0b85db34f # Color
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3396c8e7-17cf-4241-bf89-8a928a30db62
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 25c0fbe7-5180-4842-bb9e-d530e9fb2042 # Radius
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 257c065a-7a4f-4077-9390-c360f5a6a4e6
            userCondition: null
            warning: null
            width: 50
        name: Content
        uid: ffba9251-2e58-4192-9314-a197ea6fbfc8
        userCondition: null
fields:
  00e7fda5-a5ff-4422-81e4-60b0b85db34f: # Color
    columnSuffix: alfrebyw
    contentColumnType: char(7)
    fieldGroup: null
    handle: color
    instructions: 'Color of the circle around the source after it has been selected'
    name: Color
    searchable: false
    settings:
      defaultColor: '#058b8c'
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Color
  0ec5fc47-5e4f-4591-a76e-745ef7078387: # Source Type
    columnSuffix: zmhwptsb
    contentColumnType: string(9)
    fieldGroup: null
    handle: sourceType
    instructions: null
    name: 'Source Type'
    searchable: false
    settings:
      columnType: null
      options:
        -
          __assoc__:
            -
              - label
              - Supernova
            -
              - value
              - supernova
            -
              - default
              - '1'
        -
          __assoc__:
            -
              - label
              - Galaxy
            -
              - value
              - galaxy
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
  25c0fbe7-5180-4842-bb9e-d530e9fb2042: # Radius
    columnSuffix: ccyxspge
    contentColumnType: smallint(3)
    fieldGroup: null
    handle: radius
    instructions: 'Radius of the circle around the source after it is selected, measured in percent of the image width'
    name: Radius
    searchable: false
    settings:
      decimals: 0
      defaultValue: 5
      max: 100
      min: 0
      prefix: null
      previewCurrency: null
      previewFormat: decimal
      size: null
      suffix: '%'
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Number
  4941158b-702a-45b4-8da5-12ed4202efae: # Name
    columnSuffix: aoiiofwp
    contentColumnType: text
    fieldGroup: null
    handle: sourceName
    instructions: null
    name: Name
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: true
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  b23a622a-4c70-4e4d-be4a-3b2fbc739d19: # Y
    columnSuffix: cdbznkuo
    contentColumnType: smallint(3)
    fieldGroup: null
    handle: yCoord
    instructions: 'Y position, in percent, of this source on its alert image measured from the upper left corner'
    name: 'Y'
    searchable: false
    settings:
      decimals: 0
      defaultValue: null
      max: 100
      min: 0
      prefix: null
      previewCurrency: null
      previewFormat: none
      size: null
      suffix: '%'
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Number
  f7469ef4-1cc6-4236-9a47-b0a7cad50b6a: # X
    columnSuffix: exfsorqh
    contentColumnType: smallint(3)
    fieldGroup: null
    handle: xCoord
    instructions: 'X position, in percent, of this source on its alert image measured from the upper left corner'
    name: X
    searchable: false
    settings:
      decimals: 0
      defaultValue: null
      max: 100
      min: 0
      prefix: null
      previewCurrency: null
      previewFormat: none
      size: null
      suffix: '%'
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Number
handle: source
name: Source
sortOrder: 1
