field: 9d55ab75-8b96-461e-9983-552756049297 # Alert Sources
fieldLayouts:
  724e0684-8838-4013-bb87-0a758ae02a38:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 8bf7b9a2-465c-46e6-a5bf-9451b24ada88 # Source Type
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 51bb7324-7b2d-46f3-b21b-a8058e58aeaa
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 9fc55b7f-d00a-49e4-b282-4d350938f452 # X
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0f665072-7cdd-48da-966e-4820e70a6c48
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 76401484-3e66-4200-b542-6ec3fbcf6d67 # Y
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 319f8326-8fe4-4be5-8438-d477640cc900
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 0867f2df-ac4f-4178-8f78-fed2dedda051 # Color
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1aee8fd3-3a5e-4e80-9658-0eb3479e992b
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 25434ce3-3fc3-454d-95dc-6f99cd823dc3 # Radius
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 542b9dbd-394b-4370-a3c1-9a5e81a77866
            userCondition: null
            warning: null
            width: 50
        name: Content
        uid: e08eb5e7-0e69-4322-a888-654787f2daa8
        userCondition: null
fields:
  8bf7b9a2-465c-46e6-a5bf-9451b24ada88: # Source Type
    columnSuffix: hybtibyt
    contentColumnType: string(9)
    fieldGroup: null
    handle: sourceType
    instructions: null
    name: 'Source Type'
    searchable: false
    settings:
      columnType: null
      options:
        -
          __assoc__:
            -
              - label
              - Supernova
            -
              - value
              - supernova
            -
              - default
              - '1'
        -
          __assoc__:
            -
              - label
              - Galaxy
            -
              - value
              - galaxy
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
  9fc55b7f-d00a-49e4-b282-4d350938f452: # X
    columnSuffix: rpewjmah
    contentColumnType: integer(10)
    fieldGroup: null
    handle: xCoord
    instructions: 'X position, in pixels, of this source on it''s alert image'
    name: X
    searchable: false
    settings:
      decimals: 0
      defaultValue: null
      max: null
      min: null
      prefix: null
      previewCurrency: null
      previewFormat: none
      size: null
      suffix: null
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Number
  0867f2df-ac4f-4178-8f78-fed2dedda051: # Color
    columnSuffix: myysgfad
    contentColumnType: char(7)
    fieldGroup: null
    handle: color
    instructions: 'Color of the circle around the source after it has been selected'
    name: Color
    searchable: false
    settings:
      defaultColor: '#058b8c'
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Color
  25434ce3-3fc3-454d-95dc-6f99cd823dc3: # Radius
    columnSuffix: eduhsixr
    contentColumnType: integer(10)
    fieldGroup: null
    handle: radius
    instructions: 'Radius of the circle around the source after it is selected'
    name: Radius
    searchable: false
    settings:
      decimals: 0
      defaultValue: 20
      max: null
      min: 0
      prefix: null
      previewCurrency: null
      previewFormat: none
      size: null
      suffix: null
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Number
  76401484-3e66-4200-b542-6ec3fbcf6d67: # Y
    columnSuffix: ifpkuuaz
    contentColumnType: integer(10)
    fieldGroup: null
    handle: yCoord
    instructions: 'Y position, in pixels, of this source on it''s alert image'
    name: 'Y'
    searchable: false
    settings:
      decimals: 0
      defaultValue: null
      max: null
      min: null
      prefix: null
      previewCurrency: null
      previewFormat: none
      size: null
      suffix: null
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Number
handle: source
name: Source
sortOrder: 1
