field: 8b781860-2b8c-4100-969a-2f13c5272420 # Table Row
fieldLayouts:
  42907a15-1f1c-467d-b5f6-ab6726fe55c0:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 69cb131c-4118-487d-84be-d370e75627bd # Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8997b7cc-30fe-45fb-b2bc-054a304dc36c
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: fc7f5dc8-43b1-487c-8302-07abecd2429a # Equation
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 54a6712e-2188-418b-adf3-794f720c99d3
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: b4b66028-d2a4-4aae-944d-5499d9f90674
        userCondition: null
fields:
  69cb131c-4118-487d-84be-d370e75627bd: # Text
    columnSuffix: nanmdcwh
    contentColumnType: text
    fieldGroup: null
    handle: text
    instructions: null
    name: Text
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\PlainText
  fc7f5dc8-43b1-487c-8302-07abecd2429a: # Equation
    columnSuffix: lhtlrftk
    contentColumnType: text
    fieldGroup: null
    handle: equation
    instructions: 'LaTeX format input, reference the Temml documentation for help formatting: https://temml.org/docs/en/supported'
    name: Equation
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: true
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: static
name: 'Table Cell'
sortOrder: 1
