field: 4b8139b2-36be-4510-aaeb-fa8579fb3273 # Header Row
fieldLayouts:
  e2423fa9-7b5f-48b5-a7a1-7416cf69df3c:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 9d3bd0d7-b293-4e2f-9c24-0554733df011 # Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b5bd9a91-28c5-453a-9306-dd218153997d
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 53d80ba5-55f6-452a-b07e-22263269cbc8 # Equation
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 16faccd3-082c-438e-b65b-f9249fed85ea
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: a7d59e64-77d8-4b65-bf7c-fe546722b821
        userCondition: null
fields:
  9d3bd0d7-b293-4e2f-9c24-0554733df011: # Text
    columnSuffix: nebguipm
    contentColumnType: text
    fieldGroup: null
    handle: text
    instructions: null
    name: Text
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\PlainText
  53d80ba5-55f6-452a-b07e-22263269cbc8: # Equation
    columnSuffix: kobhqtyk
    contentColumnType: text
    fieldGroup: null
    handle: equation
    instructions: 'LaTeX format input, reference the Temml documentation for help formatting: https://temml.org/docs/en/supported'
    name: Equation
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: true
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: tableCell
name: 'Table Cell'
sortOrder: 1
