isPublic: true
name: 'Public Schema'
scope:
  - 'sections.3e10dcca-4dd1-4578-8add-708cd9740881:read' # Homepage
  - 'entrytypes.8145b1c9-cb8f-4c86-91ba-34fe5ded34e6:read' # Homepage
  - 'sections.959d98a5-bd20-4904-aa4c-6efb343b66e7:read' # Investigations
  - 'entrytypes.15ee50c0-15b8-44cf-9c2e-2b90ab60e109:read'
  - 'entrytypes.41225ace-a2e6-4d68-af56-d994a7d2cd20:read' # Investigation Page
  - 'sections.f1b8c943-bc12-4001-9e2a-d531379f1aaf:read' # Pages
  - 'entrytypes.23eda090-7e8e-401d-ab49-ee4becc34935:read' # Pages
  - 'volumes.7754bae8-c6eb-4fbe-882b-236621e35f2d:read' # Canto DAM
  - 'globalsets.8ccd6c1c-8e9b-44e8-93a9-f62589fb4819:read' # Site Information
  - 'usergroups.everyone:read'
  - 'categorygroups.0928ff1a-513d-41e0-acc1-606d93988618:read' # Search Filters
  - 'categorygroups.70ff59dd-8280-4bea-bef6-cfdf9ea4f0c2:read' # Sort Options
