fieldLayouts:
  e637bd11-d8e9-4c0d-9b5f-8e145c2338ef:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 475c3e84-06d8-4a5c-afca-012233f16273
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 131ceffb-300f-415d-8cd5-a932d7529287 # Read Only
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6b0bd076-9062-450b-9357-f1743ab4e476
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 6b8e1421-5b57-4c4d-bd1f-de5a2cd186e2 # Filter Color Options
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7863dfab-bccb-4c82-a6b4-0e9e81788c19
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: dfab6165-acc6-4a81-9d4a-50c69d1c1045 # Color Filter Tool Objects
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 880ac6b3-91c1-4512-b185-a338a009b6fd
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 09f25d36-d45e-4953-a876-d2a0f8a3e40d
        userCondition: null
handle: colorFilterTool
hasTitleField: true
name: 'Color Filter Tool'
section: 28704998-935a-423b-a405-d4ad8b38efa2 # Widgets
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
