fieldLayouts:
  2eeacf94-564f-439c-8ffd-75abb8001e88:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 22073c2e-9033-47e2-9523-98b40d44cda2
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 05b71c40-b1ec-4b33-ac48-b9b0c7fc81b6
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 411d7d0b-d424-40b5-b031-7949638d70ee
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: a46e7379-7773-4ce4-9c59-434567870f0c
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4a8022c6-09ae-4ebe-ba0f-a49f9f716b82
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 0481b024-bc6f-4104-bc1c-802615313aaa
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1da205b0-a3ca-4d53-b3e1-cf887c9ca02d
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 0ddca0b3-85d0-4c83-b88e-0884005e9567
        userCondition: null
handle: homepage
hasTitleField: true
name: Homepage
section: 075467b0-0dee-453c-9df0-0de6d2443cf8
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
