fieldLayouts:
  2eeacf94-564f-439c-8ffd-75abb8001e88:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 22073c2e-9033-47e2-9523-98b40d44cda2
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 40c867bb-c75a-4d5f-8d69-e7facae1c15b # Homepage Content Blocks
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 16ea4ab9-1a4a-4a64-8b32-8cdd5f5fe8ea
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 0ddca0b3-85d0-4c83-b88e-0884005e9567
        userCondition: null
handle: homepage
hasTitleField: true
name: Homepage
section: 075467b0-0dee-453c-9df0-0de6d2443cf8 # Homepage
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
