fieldLayouts:
  e86a8755-f86d-48b0-9f4f-787d41b33053:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 2663dfa8-c4ce-413b-b86b-bfa1f3477a22
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: e5142c27-2288-47b7-bfad-14cd6b3a6653 # Display Name
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c30b1ba2-8069-4629-8bc8-a18519945d31
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: a4afde15-f983-4c30-b0d7-e0b56871e4de # Dataset
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: facfe9fc-a5c1-4e50-a961-f067cf9474a6
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 11aa6c30-e830-4439-8291-7d23c7c219e7
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 8af07cbd-3ce8-4e4d-818f-261515be5ac7 # Y-axis Minimum
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9321a2e1-0a2c-42da-a3d8-b14a86bf5ae6
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 61e0fe59-d439-429c-b783-2d71fe4c5d44 # Y-axis Maximum
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8a46f79c-a6d3-45e0-9e2c-3aef24a91f0a
            userCondition: null
            warning: null
            width: 100
        name: 'Plot Configuration'
        uid: 0ea412ea-00e0-4ce5-8aef-faa4c92bcc99
        userCondition: null
handle: lightCurveTool
hasTitleField: true
name: 'Light Curve Tool'
section: 28704998-935a-423b-a405-d4ad8b38efa2 # Widgets
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: none
sortOrder: 3
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: none
