fieldLayouts:
  a39e2a68-759a-4847-adc8-a06f5ff1a228:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: b64d63bd-bd92-4eda-8758-449d6d04e924
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: f8a590d0-db30-4e06-9d6d-6cfd7613147e
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3f4f53e8-f9e8-452d-99a8-b59f284b5a4f
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: a46e7379-7773-4ce4-9c59-434567870f0c
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 39527dd3-a4c8-4a6b-8d47-f7dca9bf60bf
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 0481b024-bc6f-4104-bc1c-802615313aaa
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b981ae40-86a2-425b-9d08-af332af298a6
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: b0b13c08-cef3-4376-a3b6-350d26eaeda0
        userCondition: null
handle: pages
hasTitleField: true
name: Pages
section: 8dc1c6cb-eb37-4ad7-b9c8-7d0891fcd42d
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
