fieldLayouts:
  388e267d-df2c-4d1d-9042-d08f51a7af5e:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: c263d49d-b50a-4d39-a67a-1c11db71e9be
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: f8a590d0-db30-4e06-9d6d-6cfd7613147e # Hide Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8e551437-c9f3-4785-bb68-8a10433c9c94
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 222de7cf-741d-4d1f-b274-acc85a3c454c # Link To
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5d005e9b-49f8-4994-8657-fd61cae4e45d
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 9f955a16-12eb-48c5-88e3-c55eeb797db1
        userCondition: null
handle: redirectPage
hasTitleField: true
name: 'Redirect Page'
section: 8dc1c6cb-eb37-4ad7-b9c8-7d0891fcd42d # Pages
sortOrder: 2
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
