fieldLayouts:
  9e8d0324-0d13-49ae-a554-08d2b74185aa:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: bd2bae4a-803c-4218-97d1-5654c604686d
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: e5142c27-2288-47b7-bfad-14cd6b3a6653 # Display Name
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 552ef0ce-b6b0-4e2a-bb77-513e13f57272
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: a4afde15-f983-4c30-b0d7-e0b56871e4de # Dataset
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: cc45dfcd-e889-46fe-8ffb-d27de894632a
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 897c373a-7e95-45dd-bcb4-8b0d2d51eced
        userCondition: null
handle: sourceSelector
hasTitleField: true
name: 'Source Selector'
section: 28704998-935a-423b-a405-d4ad8b38efa2 # Widgets
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 2
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: none
