fieldLayouts:
  086a0f70-2159-4bb3-b630-40ce245f24d9:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 18f7f7f1-f4d4-4a7e-b584-4d92c078baad
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: e5142c27-2288-47b7-bfad-14cd6b3a6653 # Display Name
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f4e38025-3249-4712-9dca-e5e65e7bc6d2
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 9e1f3893-2665-42ca-a0d1-09dace40421a # Dataset
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 08fd1082-b73f-4662-9d58-d8e8fb6129e9
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 291f2cc5-c39c-4ae0-9ed3-b70a4727c5f9
        userCondition: null
handle: sourceSelector
hasTitleField: true
name: 'Source Selector'
section: 28704998-935a-423b-a405-d4ad8b38efa2 # Widgets
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: none
sortOrder: 3
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: none
