baseUrl: '@webBaseUrl/fr'
enabled: '1'
handle: fr
hasUrls: true
language: fr
name: FR
primary: false
siteGroup: 1a35bfab-6a39-4c03-b273-2d5e3151c335 # Rubin Telescope Education and Public Outreach
sortOrder: 3
