dateModified: 1687462326
email:
  fromEmail: $EMAIL_FROM_ADDRESS
  fromName: $EMAIL_SENDER_NAME
  replyToEmail: $EMAIL_REPLY_TO_ADDRESS
  template: $EMAIL_HTML_EMAIL_TEMPLATE
  transportSettings:
    host: $EMAIL_SMTP_HOST_NAME
    password: $EMAIL_SMTP_PASSWORD
    port: $EMAIL_SMTP_PORT
    useAuthentication: '1'
    username: $EMAIL_SMTP_USERNAME
  transportType: craft\mail\transportadapters\Smtp
meta:
  __names__:
    1a35bfab-6a39-4c03-b273-2d5e3151c335: 'Rubin Telescope Education and Public Outreach' # Rubin Telescope Education and Public Outreach
    2c2e1c6a-eb4d-44f1-9a43-8d79b326f354: ES # ES
    05b71c40-b1ec-4b33-ac48-b9b0c7fc81b6: Description # Description
    6f0c128e-9978-41c2-b982-dcdf3933b0e2: Homepage # Homepage
    7bd60210-4767-46b3-b735-61a1499b90b7: 'Redirect Page' # Redirect Page
    8dc1c6cb-eb37-4ad7-b9c8-7d0891fcd42d: Pages # Pages
    8f49c843-6aaa-49bf-ac19-21a9800c4760: Editors # Editors
    074f7db9-8ff3-4016-ad34-bfe9c31d5543: Pages # Pages
    77f02908-0342-4917-9d14-38f769d15c39: Pages # Pages
    90aa9610-a9c9-4531-95f8-d0068046ae25: 'Sort Options' # Sort Options
    222de7cf-741d-4d1f-b274-acc85a3c454c: 'Link To' # Link To
    461e1254-37f7-4aeb-81a1-3f08d2463d06: Students # Students
    0481b024-bc6f-4104-bc1c-802615313aaa: 'Page Type' # Page Type
    1601c7a8-2437-4b8f-b2f2-116f4c043402: 'Site Information' # Site Information
    4994da56-0831-400d-b1d1-ade611fd5da1: Title # Title
    5548ce5c-5ad4-494e-93be-8ff129618d20: Text # Text
    5599d188-862e-4717-b206-6aadd975c937: Common # Common
    075467b0-0dee-453c-9df0-0de6d2443cf8: Homepage # Homepage
    547128fa-4529-4483-9968-66425996b69f: EN # EN
    04341069-ff31-4470-970a-8c7e82ec37eb: 'Student Schema' # Student Schema
    a46e7379-7773-4ce4-9c59-434567870f0c: 'Content Blocks' # Content Blocks
    aee57b4f-2623-44fc-af2b-c670f6e1babe: 'Site information' # Site information
    c6d1924e-d9ec-4547-bb6d-bddb9b46b774: Description # Description
    c430001c-4bfc-4154-9e13-f5ada3b4a22d: Text # Text
    cec04a25-43ba-4f4c-81bd-b71f48731b5a: 'Public Schema' # Public Schema
    d8be03ce-7aeb-4141-b40e-ec39ec1c796f: Educators # Educators
    e2951ac7-e91a-4d8a-964f-50c6b6e0b1ee: 'Educator Schema' # Educator Schema
    f8a590d0-db30-4e06-9d6d-6cfd7613147e: 'Hide Title' # Hide Title
plugins:
  google-cloud:
    edition: standard
    enabled: true
    schemaVersion: '2.0'
  graphql-authentication:
    edition: standard
    enabled: true
    licenseKey: 1LUWSV7IB0M97MEVDIIFS559
    schemaVersion: 1.3.0
    settings:
      accountCooldown: 'Too many log in attempts; please try again shortly'
      accountDeleted: 'Successfully deleted account'
      accountLocked: 'Sorry, your account is currently locked'
      activationEmailSent: 'You will receive an email if it matches an account in our system'
      allowMagicAuthentication: null
      allowRegistration: '1'
      allowedFacebookDomains: null
      allowedGoogleDomains: null
      allowedMicrosoftDomains: null
      allowedTwitterDomains: null
      appleClientId: null
      appleClientSecret: null
      appleRedirectUrl: null
      appleServiceId: null
      appleServiceSecret: null
      assetMutations: null
      assetNotFound: 'We couldn''t find any matching assets'
      assetQueries: null
      emailNotInScope: 'No email in scope'
      entryMutations: null
      entryNotFound: 'We couldn''t find any matching entries'
      entryQueries: null
      facebookAppId: null
      facebookAppSecret: null
      facebookEmailMismatch: 'Email address doesn''t match allowed Facebook domains'
      facebookRedirectUrl: null
      fieldRestrictions:
        __assoc__:
          -
            - schema-1
            -
              __assoc__:
                -
                  - contentBlocks
                  - queryMutate
                -
                  - description
                  - queryMutate
                -
                  - siteDescription
                  - queryMutate
                -
                  - hideTitle
                  - queryMutate
                -
                  - linkTo
                  - queryMutate
                -
                  - pageType
                  - queryMutate
                -
                  - text
                  - queryMutate
                -
                  - siteTitle
                  - queryMutate
          -
            - 'schema-Educator Schema'
            -
              __assoc__:
                -
                  - contentBlocks
                  - queryMutate
                -
                  - description
                  - queryMutate
                -
                  - siteDescription
                  - queryMutate
                -
                  - hideTitle
                  - queryMutate
                -
                  - linkTo
                  - queryMutate
                -
                  - pageType
                  - queryMutate
                -
                  - text
                  - queryMutate
                -
                  - siteTitle
                  - queryMutate
          -
            - 'schema-Public Schema'
            -
              __assoc__:
                -
                  - contentBlocks
                  - queryMutate
                -
                  - description
                  - queryMutate
                -
                  - siteDescription
                  - queryMutate
                -
                  - hideTitle
                  - queryMutate
                -
                  - linkTo
                  - queryMutate
                -
                  - pageType
                  - queryMutate
                -
                  - text
                  - queryMutate
                -
                  - siteTitle
                  - queryMutate
          -
            - 'schema-Student Schema'
            -
              __assoc__:
                -
                  - contentBlocks
                  - queryMutate
                -
                  - description
                  - queryMutate
                -
                  - siteDescription
                  - queryMutate
                -
                  - hideTitle
                  - queryMutate
                -
                  - linkTo
                  - queryMutate
                -
                  - pageType
                  - queryMutate
                -
                  - text
                  - queryMutate
                -
                  - siteTitle
                  - queryMutate
      forbiddenField: 'User doesn''t have permission to access requested field(s)'
      forbiddenMutation: 'User doesn''t have permission to perform this mutation'
      googleClientId: null
      googleEmailMismatch: 'Email address doesn''t match allowed Google domains'
      googleTokenIdInvalid: 'Invalid Google Token ID'
      granularSchemas:
        __assoc__:
          -
            - group-3
            -
              __assoc__:
                -
                  - schemaName
                  - ''
                -
                  - allowRegistration
                  - ''
                -
                  - siteId
                  - ''
          -
            - group-4
            -
              __assoc__:
                -
                  - schemaName
                  - 'Educator Schema'
                -
                  - allowRegistration
                  - '1'
                -
                  - siteId
                  - ''
                -
                  - entryQueries
                  -
                    __assoc__:
                      -
                        - pages
                        - ''
          -
            - group-5
            -
              __assoc__:
                -
                  - schemaName
                  - 'Student Schema'
                -
                  - allowRegistration
                  - '1'
                -
                  - siteId
                  - ''
                -
                  - entryQueries
                  -
                    __assoc__:
                      -
                        - pages
                        - ''
      invalidEmailAddress: 'Invalid email address'
      invalidHeader: 'Invalid Authorization Header'
      invalidJwtSecretKey: 'Invalid JWT Secret Key'
      invalidLogin: 'We couldn''t log you in with the provided details'
      invalidMagicCode: 'Invalid magic code'
      invalidOauthToken: 'Invalid OAuth Token'
      invalidPasswordMatch: 'Passwords do not match'
      invalidPasswordUpdate: 'We couldn''t update the password with the provided details'
      invalidRefreshToken: 'Invalid Refresh Token'
      invalidRequest: 'Cannot validate request'
      invalidSchema: 'No schema has been set for this user group'
      invalidUserUpdate: 'We couldn''t update the user with the provided details'
      jwtExpiration: '30 minutes'
      jwtRefreshExpiration: '3 months'
      jwtSecretKey: 2t1eBkWF2HIzBSbP7LS9v0PZtdHvYkdB
      magicLinkSent: 'You will receive an email if it matches an account in our system'
      microsoftAppId: null
      microsoftAppSecret: null
      microsoftEmailMismatch: 'Email address doesn''t match allowed Microsoft domains'
      microsoftRedirectUrl: null
      passwordResetRequired: 'Password reset required; please check your email'
      passwordResetSent: 'You will receive an email if it matches an account in our system'
      passwordSaved: 'Successfully saved password'
      passwordUpdated: 'Successfully updated password'
      permissionType: multiple
      sameSitePolicy: strict
      schemaId: null
      schemaName: 'Public Schema'
      siteId: null
      skipActivatedCheck: ''
      skipSocialActivation: null
      tokenNotFound: 'We couldn''t find any matching tokens'
      twitterApiKey: null
      twitterApiKeySecret: null
      twitterEmailMismatch: 'Email address doesn''t match allowed Twitter domains'
      twitterRedirectUrl: null
      userActivated: 'Successfully activated user'
      userGroup: '4'
      userHasPassword: 'User not password-less'
      userNotActivated: 'Please activate your account'
      userNotFound: 'We couldn''t find any matching users'
      volumeNotFound: 'We couldn''t find any matching volumes'
  neo:
    edition: standard
    enabled: true
    licenseKey: P86UE2U77O4G56FE7414SOQB
    schemaVersion: 3.6.2
  next-builds:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
    settings:
      activeSections:
        __assoc__:
          -
            - homepage
            - '1'
          -
            - pages
            - '1'
      nextApiBaseUrl: $NEXT_API_BASE_URL
      nextSecretToken: $NEXT_REVALIDATE_SECRET_TOKEN
  redactor:
    edition: standard
    enabled: true
    schemaVersion: 2.3.0
  typedlinkfield:
    edition: standard
    enabled: true
    schemaVersion: 2.0.0
system:
  edition: pro
  live: true
  name: 'Rubin EPO Craft Project'
  retryDuration: null
  schemaVersion: 4.4.0.4
  timeZone: America/Los_Angeles
