columnSuffix: null
contentColumnType: string
fieldGroup: b0465285-e18b-4739-a3a5-cb0ec0571dd8
handle: answerOptions
instructions: null
name: 'Answer Options'
searchable: false
settings:
  contentTable: '{{%matrixcontent_answeroptions}}'
  maxBlocks: null
  minBlocks: null
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
