columnSuffix: gsgeljzc
contentColumnType: integer(10)
fieldGroup: a21a42b0-7211-4d77-9071-47a06960fef4 # Widgets
handle: binSize
instructions: null
name: 'Bin Size'
searchable: false
settings:
  decimals: 0
  defaultValue: null
  max: null
  min: 0
  prefix: null
  previewCurrency: null
  previewFormat: none
  size: null
  suffix: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Number
