columnSuffix: rgykzmpe
contentColumnType: 'decimal(11,1)'
fieldGroup: a21a42b0-7211-4d77-9071-47a06960fef4 # Widgets
handle: colorToolMax
instructions: null
name: Max
searchable: false
settings:
  decimals: 1
  defaultValue: 1.5
  max: null
  min: 0
  prefix: null
  previewCurrency: null
  previewFormat: decimal
  size: null
  suffix: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Number
