columnSuffix: stkozbee
contentColumnType: string
fieldGroup: a21a42b0-7211-4d77-9071-47a06960fef4 # Widgets
handle: colorToolTemplate
instructions: null
name: Template
searchable: false
settings:
  columnType: string
  options:
    -
      __assoc__:
        -
          - label
          - Primary
        -
          - value
          - primary
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 'Multiple Images'
        -
          - value
          - multipleImages
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 'Display Only'
        -
          - value
          - displayOnly
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Dropdown
