columnSuffix: ufnbtedv
contentColumnType: 'decimal(12,2)'
fieldGroup: e1b23b33-c33f-4c74-9811-250c2cc2789a # Data
handle: distance
instructions: null
name: Distance
searchable: false
settings:
  decimals: 2
  defaultValue: null
  max: null
  min: 0
  prefix: null
  previewCurrency: null
  previewFormat: none
  size: null
  suffix: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Number
