columnSuffix: laxydvij
contentColumnType: char
fieldGroup: a21a42b0-7211-4d77-9071-47a06960fef4 # Widgets
handle: filter
instructions: null
name: Filter
searchable: false
settings:
  columnType: null
  options:
    -
      __assoc__:
        -
          - optgroup
          - ugrizy
    -
      __assoc__:
        -
          - label
          - u
        -
          - value
          - u
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - g
        -
          - value
          - g
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - r
        -
          - value
          - r
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - i
        -
          - value
          - i
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - z
        -
          - value
          - z
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 'y'
        -
          - value
          - 'y'
        -
          - default
          - ''
    -
      __assoc__:
        -
          - optgroup
          - RGB
    -
      __assoc__:
        -
          - label
          - R
        -
          - value
          - R
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - G
        -
          - value
          - G
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - B
        -
          - value
          - B
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Dropdown
