columnSuffix: wdzuiyou
contentColumnType: text
fieldGroup: a21a42b0-7211-4d77-9071-47a06960fef4 # Widgets
handle: filterToolActions
instructions: 'Pick the actions that should be available on this tool.'
name: 'Filter Tool Actions'
searchable: false
settings:
  options:
    -
      __assoc__:
        -
          - label
          - 'Reset button'
        -
          - value
          - reset
        -
          - default
          - '1'
    -
      __assoc__:
        -
          - label
          - 'Export button'
        -
          - value
          - export
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 'Save button'
        -
          - value
          - save
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\MultiSelect
