columnSuffix: ehnqzzmf
contentColumnType: 'decimal(11,8)'
fieldGroup: e1b23b33-c33f-4c74-9811-250c2cc2789a # Data
handle: galacticLongitude
instructions: 'Galactic longitude, in degrees'''
name: 'Galactic longitude'
searchable: false
settings:
  decimals: 8
  defaultValue: null
  max: 360
  min: 0
  prefix: null
  previewCurrency: null
  previewFormat: none
  size: null
  suffix: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Number
