columnSuffix: wzyfdnwf
contentColumnType: smallint(2)
fieldGroup: e1b23b33-c33f-4c74-9811-250c2cc2789a # Data
handle: galacticLatitude
instructions: 'Galactic latitude, in degrees'
name: 'Galactic Latitude'
searchable: false
settings:
  decimals: 0
  defaultValue: null
  max: 90
  min: -90
  prefix: null
  previewCurrency: null
  previewFormat: none
  size: null
  suffix: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Number
