columnSuffix: null
contentColumnType: string
fieldGroup: a21a42b0-7211-4d77-9071-47a06960fef4
handle: graphBars
instructions: null
name: 'Graph Bars'
searchable: false
settings:
  contentTable: '{{%matrixcontent_graphbars}}'
  maxBlocks: null
  minBlocks: null
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
