columnSuffix: uwgsrdeu
contentColumnType: boolean
fieldGroup: 074f7db9-8ff3-4016-ad34-bfe9c31d5543
handle: hideTitle
instructions: null
name: 'Hide Title'
searchable: false
settings:
  default: false
  offLabel: show
  onLabel: hide
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
