columnSuffix: nuzumixp
contentColumnType:
  - 'cantoId:string'
  - 'cantoAlbumId:string'
  - 'cantoAssetData:text'
  - 'cantoAlbumData:string'
fieldGroup: 5599d188-862e-4717-b206-6aadd975c937
handle: image
instructions: null
name: Image
searchable: false
settings:
  cantoAssetPickerType: singleImagePicker
translationKeyFormat: null
translationMethod: site
type: lsst\cantodamassets\fields\CantoDamAsset
