columnSuffix: ywrotzto
contentColumnType:
  - 'cantoId:string'
  - 'cantoAlbumId:string'
  - 'cantoAssetData:json'
  - 'cantoAlbumData:json'
fieldGroup: 4e1884f2-7cc9-40d8-8426-f66da625d8cc # Assets
handle: imageAlbum
instructions: 'Select contents of an entire Canto album.'
name: 'Image Album'
searchable: false
settings:
  cantoAssetPickerType: wholeAlbumPicker
translationKeyFormat: null
translationMethod: none
type: lsst\cantodamassets\fields\CantoDamAsset
