columnSuffix: gjnqolwr
contentColumnType: boolean
fieldGroup: a21a42b0-7211-4d77-9071-47a06960fef4 # Widgets
handle: includeScatterPlot
instructions: null
name: 'Include Scatter Plot'
searchable: false
settings:
  default: false
  offLabel: null
  onLabel: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
