columnSuffix: bwblnugr
contentColumnType: boolean
fieldGroup: a21a42b0-7211-4d77-9071-47a06960fef4 # Widgets
handle: isActive
instructions: null
name: isActive
searchable: false
settings:
  default: false
  offLabel: Inactive
  onLabel: Active
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
