columnSuffix: ewyzlaiq
contentColumnType: boolean
fieldGroup: a21a42b0-7211-4d77-9071-47a06960fef4 # Widgets
handle: isEnabled
instructions: null
name: isEnabled
searchable: false
settings:
  default: true
  offLabel: Disabled
  onLabel: Enabled
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
