columnSuffix: uibuvada
contentColumnType: smallint(1)
fieldGroup: e1b23b33-c33f-4c74-9811-250c2cc2789a # Data
handle: precision
instructions: null
name: Precision
searchable: false
settings:
  decimals: 0
  defaultValue: 0
  max: 6
  min: 0
  prefix: null
  previewCurrency: null
  previewFormat: none
  size: null
  suffix: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Number
