columnSuffix: letxbuph
contentColumnType: string
fieldGroup: a21a42b0-7211-4d77-9071-47a06960fef4 # Widgets
handle: preSelectedColor
instructions: null
name: 'Pre-selected Color'
searchable: false
settings:
  options:
    -
      __assoc__:
        -
          - label
          - None
        -
          - value
          - none
        -
          - default
          - '1'
translationKeyFormat: null
translationMethod: site
type: craft\fields\Dropdown
