columnSuffix: null
contentColumnType: string
fieldGroup: b0465285-e18b-4739-a3a5-cb0ec0571dd8 # Questions
handle: questionWidgetsBlock
instructions: null
name: 'Question Widgets'
searchable: false
settings:
  maxBlocks: 1
  maxLevels: null
  maxTopBlocks: null
  minBlocks: 1
  minLevels: null
  minTopBlocks: null
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: benf\neo\Field
