columnSuffix: rlojoiyn
contentColumnType: text
fieldGroup: b0465285-e18b-4739-a3a5-cb0ec0571dd8 # Questions
handle: questionText
instructions: null
name: 'Question Text'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: false
  columnType: null
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: site
type: craft\fields\PlainText
