columnSuffix: null
contentColumnType: string
fieldGroup: 5599d188-862e-4717-b206-6aadd975c937 # Common
handle: tableHeader
instructions: null
name: 'Table Header'
searchable: false
settings:
  blockTypeFields: 0
  changedFieldIndicator: 1790871278
  columns:
    __assoc__:
      -
        - 4b8139b2-36be-4510-aaeb-fa8579fb3273 # Header Row
        -
          __assoc__:
            -
              - width
              - ''
  contentTable: '{{%stc_tableheader}}'
  fieldLayout: table
  maxRows: null
  minRows: null
  propagationKeyFormat: null
  propagationMethod: all
  selectionLabel: null
  staticField: true
translationKeyFormat: null
translationMethod: none
type: verbb\supertable\fields\SuperTableField
