columnSuffix: hempumxf
contentColumnType: text
fieldGroup: 75965c47-b816-42c0-8e07-d1fdcd44fba5 # Data
handle: uniqueId
instructions: 'A unique data identifier'
name: 'Unique ID'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: true
  columnType: null
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
