columnSuffix: null
contentColumnType: string
fieldGroup: b0465285-e18b-4739-a3a5-cb0ec0571dd8 # Questions
handle: validation
instructions: null
name: Validation
searchable: false
settings:
  contentTable: '{{%matrixcontent_validation}}'
  maxBlocks: null
  minBlocks: null
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
