changedFieldIndicator: 1538629749
field: f633c7c8-51d2-4e26-93a0-630d539e83f7 # Table Header
fieldLayouts:
  c79b7d1b-5646-44ad-b454-55fafd5835ec:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 4b8139b2-36be-4510-aaeb-fa8579fb3273 # Header Row
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8f7c21fa-32c5-44b7-b97d-644d056b0eaf
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: e6eddf2b-8885-4ba0-b0f3-b9b79149c8a6
        userCondition: null
fields:
  4b8139b2-36be-4510-aaeb-fa8579fb3273: # Header Row
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: headerRow
    instructions: null
    name: 'Header Row'
    searchable: false
    settings:
      contentTable: '{{%matrixcontent_headerrow}}'
      maxBlocks: null
      minBlocks: null
      propagationKeyFormat: null
      propagationMethod: all
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Matrix
