changedFieldIndicator: 1251074599
field: fcc60644-81ac-4f94-ad34-8bdaeeb4a6b6 # Question Table
fieldLayouts:
  23b36afb-80c5-40ea-b3bd-8ff3e6f89cc3:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 8b781860-2b8c-4100-969a-2f13c5272420 # Table Row
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9bfbc7a7-059e-4859-98a2-e5055bb92313
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: c303c206-12f9-48cc-b96a-dace930eae6e
        userCondition: null
fields:
  8b781860-2b8c-4100-969a-2f13c5272420: # Table Row
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: tableCell
    instructions: 'Enter either text or a question in each cell.'
    name: 'Table Row'
    searchable: false
    settings:
      contentTable: '{{%matrixcontent_tablecell}}'
      maxBlocks: null
      minBlocks: null
      propagationKeyFormat: null
      propagationMethod: all
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Matrix
