defaultPlacement: end
enableVersioning: true
handle: referenceContent
name: 'Reference Content'
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  2c2e1c6a-eb4d-44f1-9a43-8d79b326f354: # ES
    enabledByDefault: true
    hasUrls: true
    template: null
    uriFormat: 'reference/{slug}'
  356c97b0-54e5-44bb-901e-9d92a314134f: # FR
    enabledByDefault: true
    hasUrls: true
    template: null
    uriFormat: 'reference/{slug}'
  547128fa-4529-4483-9968-66425996b69f: # EN
    enabledByDefault: true
    hasUrls: true
    template: null
    uriFormat: 'reference/{slug}'
type: channel
