childBlocks: null
conditions: null
description: ''
enabled: true
field: a46e7379-7773-4ce4-9c59-434567870f0c # Content Blocks
fieldLayouts:
  6f9cf580-cfe8-481f-888e-23d4701ffd9f:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: c430001c-4bfc-4154-9e13-f5ada3b4a22d # Text
            instructions: null
            label: Title
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 71d7f4f0-767c-4d29-ae1f-e1b5fe113a56
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: d9df041c-3556-450e-94e1-f37369daf5f3 # X-axis Label
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 683e825c-38ca-4dd9-b8a7-7e75dd27e985
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 852df24b-f90e-486b-a371-b47ca241a84e # Y-axis Label
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7db2463b-9664-4002-b1cc-5dd1ffe5a149
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 8af07cbd-3ce8-4e4d-818f-261515be5ac7 # Y-axis Minimum
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f15f5e5d-1e86-47c4-9d52-067ac196264c
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 61e0fe59-d439-429c-b783-2d71fe4c5d44 # Y-axis Maximum
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 30c3bdca-a6d7-446d-820c-9bd9ff65cf97
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 17b9b8a2-978a-4cd8-a7da-f5b3d77e1ed3 # Graph Bars
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c65cd527-f57f-4f51-a78a-70d801cb7d2c
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 6eb93f0e-4432-4dec-89a8-ea1f20480881
        userCondition: null
group: 513634e9-3389-4e41-b769-9433ac34e35e # Widgets
groupChildBlockTypes: true
handle: barGraphTool
icon: null
ignorePermissions: true
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
minBlocks: 0
minChildBlocks: 0
minSiblingBlocks: 0
name: 'Bar Graph Tool'
sortOrder: 13
topLevel: true
