childBlocks: null
conditions: null
description: ''
enabled: true
field: a46e7379-7773-4ce4-9c59-434567870f0c # Content Blocks
fieldLayouts:
  38b55090-91bb-4ecd-898b-184411568fb3:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 241a63ec-3137-4b6a-be7d-27714391c346 # Camera Filter Tool
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d2ef506d-36c1-442a-b5f4-4f8b21b43e53
            userCondition: null
            warning: null
            width: 100
        name: '1'
        uid: 1cf0d7a8-0c4d-4599-8e06-42c0e7528b8a
        userCondition: null
group: 513634e9-3389-4e41-b769-9433ac34e35e # Widgets
groupChildBlockTypes: true
handle: cameraFilterToolBlock
icon: null
ignorePermissions: true
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
minBlocks: 0
minChildBlocks: 0
minSiblingBlocks: 0
name: 'Camera Filter Tool Block'
sortOrder: 15
topLevel: true
