childBlocks: null
conditions: null
description: 'Interactive tool for displaying the range of each filter in the Rubin Observatory LSST camera'
enabled: true
field: a46e7379-7773-4ce4-9c59-434567870f0c # Content Blocks
group: 513634e9-3389-4e41-b769-9433ac34e35e # Widgets
groupChildBlockTypes: true
handle: cameraFilterTool
icon: null
ignorePermissions: true
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
minBlocks: 0
minChildBlocks: 0
minSiblingBlocks: 0
name: 'Camera Filter Tool'
sortOrder: 15
topLevel: true
