childBlocks:
  - questionBlock
  - text
  - table
  - image
  - group
  - barGraphTool
  - filterTool
  - scatterplotTool
  - cameraFilterTool
  - colorFilterToolBlock
  - cameraFilterToolBlock
  - colorTool
conditions: null
description: ''
enabled: true
field: a46e7379-7773-4ce4-9c59-434567870f0c # Content Blocks
group: 7ebe493b-5e03-48c8-8375-c9f9582da77e # Containers
groupChildBlockTypes: true
handle: colLeft
icon: null
ignorePermissions: true
maxBlocks: 1
maxChildBlocks: 0
maxSiblingBlocks: 0
minBlocks: 0
minChildBlocks: 0
minSiblingBlocks: 0
name: 'Left Column'
sortOrder: 9
topLevel: false
