childBlocks: null
conditions: null
description: ''
enabled: true
field: a46e7379-7773-4ce4-9c59-434567870f0c # Content Blocks
fieldLayouts:
  dc576cae-30e9-4029-b574-433c7403cf1d:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: c6109150-a89c-4f0b-aa79-8c1ca78be0ec # Template
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: cfe0e1c7-2b86-4aa4-95d0-202e88bc5257
            userCondition: null
            warning: null
            width: 75
          -
            elementCondition: null
            fieldUid: 131ceffb-300f-415d-8cd5-a932d7529287 # Read Only
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 199847a1-9e41-4e91-aaab-19247a34fb5a
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition:
              class: benf\neo\elements\conditions\BlockCondition
              conditionRules:
                -
                  class: craft\fields\conditions\OptionsFieldConditionRule
                  fieldUid: c6109150-a89c-4f0b-aa79-8c1ca78be0ec # Template
                  operator: in
                  uid: c0f19587-32fa-4c3e-969f-09c42cf85cd8
                  values:
                    - primary
                    - displayOnly
              elementType: benf\neo\elements\Block
              fieldContext: global
            fieldUid: c22e4947-7fbb-488a-994f-246c31e27b95 # Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8d410382-4204-4256-857c-06bd91cada13
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition:
              class: benf\neo\elements\conditions\BlockCondition
              conditionRules:
                -
                  class: craft\fields\conditions\OptionsFieldConditionRule
                  fieldUid: c6109150-a89c-4f0b-aa79-8c1ca78be0ec # Template
                  operator: in
                  uid: 4a741494-eae5-4407-b1ec-715379e26d0a
                  values:
                    - multipleImages
              elementType: benf\neo\elements\Block
              fieldContext: global
            fieldUid: 9fc49630-8ca5-4f95-be3e-cf1adc06e008 # Images
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 411866f9-c2bc-4775-bf82-3fca61122ba7
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 7c9a9947-5bf7-4b38-9e3f-104ac356feca
        userCondition: null
group: 513634e9-3389-4e41-b769-9433ac34e35e # Widgets
groupChildBlockTypes: true
handle: colorTool
icon: null
ignorePermissions: true
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
minBlocks: 0
minChildBlocks: 0
minSiblingBlocks: 0
name: 'Color Tool'
sortOrder: 12
topLevel: true
