childBlocks: null
conditions: null
description: 'Mathematical equation'
enabled: true
field: a46e7379-7773-4ce4-9c59-434567870f0c # Content Blocks
fieldLayouts:
  4317e51b-a554-4107-8929-70f27dbad4f6:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: bf080076-0029-4fb7-9562-4da97d31c0b4 # LaTeX
            instructions: 'LaTeX format input, reference the Temml documentation for help formatting: https://temml.org/docs/en/supported'
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4533dacc-7e3b-4879-95aa-3cb13c875278
            userCondition: null
            warning: null
            width: 100
        name: 'Tab 1'
        uid: 66641481-a919-4ae4-9632-e146c1530f72
        userCondition: null
group: null
groupChildBlockTypes: true
handle: equation
icon: null
iconFilename: ''
ignorePermissions: true
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
minBlocks: 0
minChildBlocks: 0
minSiblingBlocks: 0
name: Equation
topLevel: true
