childBlocks: null
conditions: null
description: ''
enabled: true
field: a46e7379-7773-4ce4-9c59-434567870f0c # Content Blocks
fieldLayouts:
  598fada8-a9b9-4f53-b446-ce1981afaf7e:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: d0f08c4c-40d1-444d-9a32-b1264d617636 # Pre-selected Color
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8f72c938-d70c-4466-b9ce-7508327496ac
            userCondition: null
            warning: null
            width: 75
          -
            elementCondition: null
            fieldUid: 131ceffb-300f-415d-8cd5-a932d7529287 # Read Only
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c0f7d268-66af-41ff-bf16-5ef40896345b
            userCondition: null
            warning: null
            width: 25
        name: Content
        uid: 9b6809bf-ed9f-43c6-b8a4-f93cdde5a5f5
        userCondition: null
group: 513634e9-3389-4e41-b769-9433ac34e35e # Widgets
groupChildBlockTypes: true
handle: filterTool
icon: null
ignorePermissions: true
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
minBlocks: 0
minChildBlocks: 0
minSiblingBlocks: 0
name: 'Filter Tool'
sortOrder: 13
topLevel: true
