childBlocks:
  - questionBlock
  - text
  - image
  - widgetContainer
  - barGraphTool
  - colorTool
  - filterTool
  - scatterplotTool
conditions: null
description: ''
enabled: true
field: a46e7379-7773-4ce4-9c59-434567870f0c # Content Blocks
group: 7ebe493b-5e03-48c8-8375-c9f9582da77e # Containers
groupChildBlockTypes: true
handle: group
icon: null
ignorePermissions: true
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
minBlocks: 0
minChildBlocks: 0
minSiblingBlocks: 0
name: 'Interaction Group'
sortOrder: 5
topLevel: true
