childBlocks:
  - object
conditions: null
description: ''
enabled: true
field: dfab6165-acc6-4a81-9d4a-50c69d1c1045 # Color Filter Tool Objects
fieldLayouts:
  1b6f6db3-a430-407d-90a8-a17036aa55c2:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: d05be14c-5b5b-446d-968c-ad6af1ef322c # Group Name
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d617d42e-d90d-4cb3-8632-86dd3419f9ea
            userCondition: null
            warning: null
            width: 50
        name: '1'
        uid: fe1998cf-edee-441a-8727-f67b2778a857
        userCondition: null
group: null
groupChildBlockTypes: true
handle: group
icon: null
ignorePermissions: true
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
minBlocks: 0
minChildBlocks: 0
minSiblingBlocks: 0
name: Group
topLevel: true
