childBlocks: null
conditions: null
description: ''
enabled: true
field: a46e7379-7773-4ce4-9c59-434567870f0c # Content Blocks
fieldLayouts:
  27dac77a-8279-4e5d-80ca-d7be8e2ad0a8:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: c22e4947-7fbb-488a-994f-246c31e27b95 # Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5274b8d7-2ddc-4951-93c4-a3ba13ff5204
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: dd4f7c39-ff32-47e4-b4eb-129bbf44b4a7 # Caption
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 532503d1-b81c-459e-9455-fc30d2f25cf5
            userCondition: null
            warning: null
            width: 100
        name: 'Tab 1'
        uid: af932c0e-cb2a-4cf8-8975-29f6875fb4c5
        userCondition: null
group: null
groupChildBlockTypes: true
handle: image
icon: null
ignorePermissions: true
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
minBlocks: 0
minChildBlocks: 0
minSiblingBlocks: 0
name: Image
sortOrder: 2
topLevel: true
