childBlocks: null
conditions: null
description: ''
enabled: true
field: a46e7379-7773-4ce4-9c59-434567870f0c # Content Blocks
fieldLayouts:
  da781a71-b62c-4252-9ff5-31d7fa528228:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: c22e4947-7fbb-488a-994f-246c31e27b95 # Image
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: daf6ca48-a51c-408b-a898-381be6c31f30
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 27af84b2-9ccb-416c-ae38-872fdca1f5c0 # Layout
            instructions: 'Shows the caption underneath the image (vertical) or next to the image (horizontal)'
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2e979c28-bafa-4fef-8d5a-91a8c15d8e0e
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: bad8a706-ea60-4282-b1da-3c9ee5f2111a # Caption
            instructions: 'Optional caption that will override the caption generated by Canto. If left empty, the caption will used the caption and credit in Canto.'
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3f5474a8-83ec-4ca4-b431-33fe672203ae
            userCondition: null
            warning: null
            width: 100
        name: 'Tab 1'
        uid: af932c0e-cb2a-4cf8-8975-29f6875fb4c5
        userCondition: null
group: null
groupChildBlockTypes: true
handle: image
icon: null
ignorePermissions: true
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
minBlocks: 0
minChildBlocks: 0
minSiblingBlocks: 0
name: Image
sortOrder: 4
topLevel: true
