childBlocks: null
conditions: null
description: ''
enabled: true
field: 2599f40c-bfbc-4db6-bf56-cb9f48ad01bf # Question Widgets Block
fieldLayouts:
  7567a7a3-3550-4a3c-b376-3d3b28f606f9:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: e5142c27-2288-47b7-bfad-14cd6b3a6653 # Display Name
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 00746e6a-31ad-464d-9d3d-03d60eb7c727
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: a4afde15-f983-4c30-b0d7-e0b56871e4de # Dataset
            instructions: 'Selecting multiple datasets will give users a randomly selected dataset.'
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 02cc540b-696b-40f8-9b79-ffa16236c17c
            userCondition: null
            warning: null
            width: 100
        name: Configuration
        uid: 2ad4cca8-9637-43e6-b879-9c4e6145546a
        userCondition: null
group: 6efbdc96-00f5-4e37-953b-d36344f6e1fb # Configured Widgets
groupChildBlockTypes: true
handle: isochronePlot
icon: null
iconFilename: ''
ignorePermissions: true
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
minBlocks: 0
minChildBlocks: 0
minSiblingBlocks: 0
name: 'Isochrone Plot'
topLevel: true
