childBlocks: null
conditions: null
description: ''
enabled: true
field: a46e7379-7773-4ce4-9c59-434567870f0c # Content Blocks
fieldLayouts:
  a02dbc96-7e04-4fc7-bf73-ccc523ed3a62:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 466246f6-753b-4198-8067-18acf1a7d4cb
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6fe1e356-d221-43d2-9039-efdae1729f70
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 729b9a44-aadb-492d-91e3-bb55e97959c6
        userCondition: null
group: 513634e9-3389-4e41-b769-9433ac34e35e # Widgets
groupChildBlockTypes: true
handle: magnitudeScatterPlot
icon: null
iconFilename: ''
ignorePermissions: true
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
minBlocks: 0
minChildBlocks: 0
minSiblingBlocks: 0
name: 'Magnitude Scatter Plot'
topLevel: true
