childBlocks:
  - filterimage
conditions: null
description: ''
enabled: true
field: dfab6165-acc6-4a81-9d4a-50c69d1c1045 # Color Filter Tool Objects
fieldLayouts:
  ae9b2834-df91-403f-a153-15ab050e742d:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: dd362aa4-c24c-4d2f-a867-d0baceacd50d # Object Name
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9a378491-e060-4ff0-b21f-88f01abdba25
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: c49579aa-2d5c-4b05-a9f0-153bb0830d8e # Object Caption
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5b2e5bd6-f168-436f-af6d-38fd3f8e9559
            userCondition: null
            warning: null
            width: 50
        name: '1'
        uid: dc1f3be9-15e1-4e6e-8b1d-0c2dc84270f0
        userCondition: null
group: null
groupChildBlockTypes: true
handle: object
icon: null
ignorePermissions: true
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
minBlocks: 0
minChildBlocks: 0
minSiblingBlocks: 0
name: Object
sortOrder: 2
topLevel: false
