childBlocks: null
conditions: null
description: ''
enabled: true
field: a46e7379-7773-4ce4-9c59-434567870f0c # Content Blocks
fieldLayouts:
  ace218fb-2b69-447d-ae82-ae73542df077:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 9b29c2f8-e229-419f-b6fa-48f5307ebf34 # Question Entries
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5379f2fb-f51c-4948-a604-2a4714a954b2
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 22ec9496-a089-4732-bace-b53ebdfe3fe9
        userCondition: null
group: null
groupChildBlockTypes: true
handle: questionBlock
icon: null
iconFilename: ''
ignorePermissions: true
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
minBlocks: 0
minChildBlocks: 0
minSiblingBlocks: 0
name: 'Question Block'
topLevel: true
