childBlocks: null
conditions: null
description: 'Readonly text that makes up the question'
enabled: true
field: 29f139cc-2d9b-4e10-afce-1e6a70105e2b # Multi-part Blocks
fieldLayouts:
  a8d8e75e-0128-43f4-9f1e-48b8e0d92e2c:
    tabs:
      -
        elementCondition: null
        elements:
          -
            dismissible: true
            elementCondition: null
            style: tip
            tip: 'This block adds question text to a question, to add a text input field use the "Text" block grouped under "Question Parts"'
            type: craft\fieldlayoutelements\Tip
            uid: 37d8336e-0631-44ed-8f63-f0524cabc57e
            userCondition: null
          -
            elementCondition: null
            fieldUid: 919ed98f-d33e-4fae-adc0-2253a155246f # Question Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c72eea43-0bef-46c9-b49d-6d6cb56f4fc8
            userCondition: null
            warning: null
            width: 100
        name: Input
        uid: 6e78ea22-3417-48f1-90b4-caea7187da19
        userCondition: null
group: null
groupChildBlockTypes: true
handle: readonlyText
icon: null
ignorePermissions: true
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
minBlocks: 0
minChildBlocks: 0
minSiblingBlocks: 0
name: 'Question Text'
topLevel: true
