childBlocks: null
conditions: null
description: ''
enabled: true
field: a46e7379-7773-4ce4-9c59-434567870f0c # Content Blocks
fieldLayouts:
  b4f196ac-ace4-4c1b-8abd-a3a1adb269b4:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 55ef91b0-a2ba-4935-8d49-9e3e1d3dcc91 # Reference Modal Entries
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8b0db4fa-ce93-4bc6-b859-faab823894d0
            userCondition: null
            warning: null
            width: 100
        name: 'Tab 1'
        uid: 206af2d5-6e44-4a8f-a6be-2e25fb61e8e7
        userCondition: null
group: null
groupChildBlockTypes: true
handle: referenceModalBlock
icon: null
ignorePermissions: true
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
minBlocks: 0
minChildBlocks: 0
minSiblingBlocks: 0
name: 'Reference Modal Block'
topLevel: true
