childBlocks: null
conditions: null
description: ''
enabled: true
field: 2599f40c-bfbc-4db6-bf56-cb9f48ad01bf # Question Widgets Block
fieldLayouts:
  3e1457ad-5a37-438c-bc49-f395b7b82cd1:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: e17c94af-1953-42af-939c-e3ed84c62a95 # Source Selector
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 18b5c6dc-eddb-4aa9-9857-a2d97305259a
            userCondition: null
            warning: null
            width: 100
        name: Widget
        uid: 718a750c-8f89-48f2-aaf5-67507bed2734
        userCondition: null
group: 6efbdc96-00f5-4e37-953b-d36344f6e1fb # Configured Widgets
groupChildBlockTypes: true
handle: sourceSelectorBlock
icon: null
iconFilename: ''
ignorePermissions: true
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
minBlocks: 0
minChildBlocks: 0
minSiblingBlocks: 0
name: 'Source Selector Block'
topLevel: true
