childBlocks: null
conditions: null
description: ''
enabled: true
field: a46e7379-7773-4ce4-9c59-434567870f0c # Content Blocks
fieldLayouts:
  55ca28cd-8e26-4b12-938b-9256209bdb9f:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 0fd14cd3-7b23-4230-adce-9cfa16050740 # Widget Instructions
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a93f7dd4-641a-46e3-a513-426cb413a698
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 4a4c9cae-254c-4307-ba31-9b3a6b19b404 # JSON
            instructions: 'Count of supernovae in each bin'
            label: Bins
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7931a6de-3d69-4fe1-83ad-a243eebfb6c8
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 1af829d6-64f9-4d22-8ac5-87c7888242a2 # Step
            instructions: 'Size of each bin'
            label: 'Bin size'
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ac0cf41b-c938-403b-8619-949346762c38
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 0e9051be-b451-4b7e-ac51-57078cf73ec5 # Image Album
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4e5ec570-3a87-4b5a-954c-05ff73108293
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 9e1f3893-2665-42ca-a0d1-09dace40421a # Dataset
            instructions: 'Supernovae referenced from other areas of the investigation'
            label: 'User datapoints'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: daf02dc6-3670-427f-bdc1-6b9288d86c8f
            userCondition: null
            warning: null
            width: 50
        name: Data
        uid: fd0f5017-4780-4693-8f0d-5b51ff274f09
        userCondition: null
group: 513634e9-3389-4e41-b769-9433ac34e35e # Widgets
groupChildBlockTypes: true
handle: supernovaThreeVector
icon: null
iconFilename: ''
ignorePermissions: true
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
minBlocks: 0
minChildBlocks: 0
minSiblingBlocks: 0
name: 'Supernova Three Vector'
topLevel: true
