childBlocks: null
conditions: null
description: ''
enabled: true
field: a46e7379-7773-4ce4-9c59-434567870f0c # Content Blocks
fieldLayouts:
  121174ff-1469-41e0-8458-7e3461b11123:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: fdde6af5-dd6a-4587-8182-a1dea7793f95
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ef35e0dc-330d-4e4e-ab35-9e0432f4c31c
            userCondition: null
            warning: null
            width: 100
        name: 'Tab 1'
        uid: b68806bd-054d-4d97-b747-37f152aa3e83
        userCondition: null
group: null
groupChildBlockTypes: true
handle: table
icon: null
ignorePermissions: true
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
minBlocks: 0
minChildBlocks: 0
minSiblingBlocks: 0
name: Table
sortOrder: 3
topLevel: true
