childBlocks: null
conditions: null
description: ''
enabled: true
field: a46e7379-7773-4ce4-9c59-434567870f0c # Content Blocks
fieldLayouts:
  b3fc2a5b-fe16-4976-bb25-14d81302f9d9:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: c430001c-4bfc-4154-9e13-f5ada3b4a22d # Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ccba26ac-5eec-40a9-b6c2-ac8902ea0dd7
            userCondition: null
            warning: null
            width: 100
        name: 'Tab 1'
        uid: 86e5c25c-9fa9-41f6-83d7-60cedf48abab
        userCondition: null
group: null
groupChildBlockTypes: true
handle: text
icon: null
iconFilename: ''
ignorePermissions: true
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
minBlocks: 0
minChildBlocks: 0
minSiblingBlocks: 0
name: Text
topLevel: true
