childBlocks: null
conditions: null
description: 'Text input field'
enabled: true
field: 29f139cc-2d9b-4e10-afce-1e6a70105e2b # Multi-part Blocks
fieldLayouts:
  d91a3fc5-64f8-4138-ae9a-e14b64909f7b:
    tabs:
      -
        elementCondition: null
        elements:
          -
            dismissible: false
            elementCondition: null
            style: tip
            tip: 'This block adds an empty text input, to add a string of text to the question use the "Question Text" block.'
            type: craft\fieldlayoutelements\Tip
            uid: 3f93308b-3faa-48d1-8be4-ecb5a3ed580b
            userCondition: null
        name: Input
        uid: a72fa7dc-2e06-42e7-b403-99b7bf20c0fa
        userCondition: null
group: f8832ac4-1064-4c31-9390-109641d13d12 # Question Parts
groupChildBlockTypes: true
handle: text
icon: null
ignorePermissions: true
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
minBlocks: 0
minChildBlocks: 0
minSiblingBlocks: 0
name: Text
topLevel: true
