childBlocks: null
conditions: null
description: ''
enabled: true
field: a46e7379-7773-4ce4-9c59-434567870f0c # Content Blocks
fieldLayouts:
  84881e5b-481f-4739-bc8e-635abbde5d80:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 118a3e01-4188-4f83-be5b-f4ce24d7513e # Video
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 15384192-7122-41b6-b22f-ede33ad5be64
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: bad8a706-ea60-4282-b1da-3c9ee5f2111a # Caption
            instructions: 'Caption that will override any text fields in Canto'
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c620d1af-c204-470d-bcf3-5164242224fb
            userCondition: null
            warning: null
            width: 100
        name: 'Tab 1'
        uid: 320531a7-9075-4282-91b3-c245e887568a
        userCondition: null
group: null
groupChildBlockTypes: true
handle: video
icon: null
ignorePermissions: true
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
minBlocks: 0
minChildBlocks: 0
minSiblingBlocks: 0
name: Video
sortOrder: 7
topLevel: true
