childBlocks: null
conditions: null
description: ''
enabled: true
field: a46e7379-7773-4ce4-9c59-434567870f0c # Content Blocks
fieldLayouts:
  fc4ef7d1-7c04-460c-b2c3-8810bc20877e:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 71b3bf66-70f5-4af6-8020-aab77b765608 # Video
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1a00ff25-4978-4a3b-8bd0-6cafc97db572
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: bad8a706-ea60-4282-b1da-3c9ee5f2111a # Caption
            instructions: 'Caption that will override any text fields in Canto'
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1f268bcf-8fda-4433-ad13-cb5912c9238e
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: c4454539-c458-4a11-acc8-bc2868d31db1
        userCondition: null
group: null
groupChildBlockTypes: true
handle: video
icon: null
iconFilename: ''
ignorePermissions: true
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
minBlocks: 0
minChildBlocks: 0
minSiblingBlocks: 0
name: Video
topLevel: true
